#!/usr/bin/env python3
"""
Generate watermarked PDFs in the same directory as source files
"""

import os
import sys
import json
import subprocess
from datetime import datetime
from pathlib import Path

# Add scripts directory to path
sys.path.append(str(Path(__file__).parent))
from watermark import add_watermark_to_pdf

def convert_to_pdf(md_path):
    """Convert markdown to PDF using pandoc"""
    md_path = Path(md_path).resolve()
    
    # Output PDF in same directory as markdown
    pdf_path = md_path.with_suffix('.pdf')
    
    cmd = [
        'pandoc', str(md_path),
        '-o', str(pdf_path),
        '--pdf-engine=xelatex',
        '-V', 'geometry:margin=1in',
        '-V', 'fontsize=11pt',
        '--toc', '--toc-depth=3',
        '--standalone',
        '--quiet'
    ]
    
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    if result.returncode != 0:
        print(f"❌ Pandoc failed: {result.stderr}")
        return None
    
    return pdf_path

def main():
    # Get files from environment
    files_json = os.environ.get('FILES_JSON', '[]')
    
    try:
        files = json.loads(files_json)
    except json.JSONDecodeError:
        print("Error: Invalid JSON in FILES_JSON")
        sys.exit(1)
    
    if not files:
        print("No files to process")
        print("pdf_count=0")
        sys.exit(0)
    
    # Generate watermark
    actor = os.environ.get('ACTOR', 'unknown-user')
    timestamp = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
    custom_watermark = os.environ.get('CUSTOM_WATERMARK', '')
    
    watermark_text = custom_watermark if custom_watermark else f"Generated by {actor} on {timestamp}"
    
    print(f"Processing {len(files)} file(s)")
    print(f"Watermark: {watermark_text}")
    
    generated = 0
    
    for md_file in files:
        md_path = Path(md_file)
        
        if not md_path.exists():
            print(f"❌ File not found: {md_file}")
            continue
        
        print(f"\n📄 Processing: {md_file}")
        
        # Convert to PDF
        pdf_path = convert_to_pdf(md_path)
        if not pdf_path:
            continue
        
        # Add watermark
        temp_watermarked = pdf_path.with_suffix('.tmp.pdf')
        try:
            add_watermark_to_pdf(str(pdf_path), str(temp_watermarked), watermark_text)
            
            if temp_watermarked.exists():
                temp_watermarked.replace(pdf_path)
                print(f"✅ Generated: {pdf_path.name}")
                generated += 1
            else:
                print(f"❌ Watermarking failed")
                pdf_path.unlink(missing_ok=True)
        except Exception as e:
            print(f"❌ Error: {e}")
            pdf_path.unlink(missing_ok=True)
    
    # Set output for GitHub Actions
    print(f"\nGenerated {generated} PDF(s)")
    with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
        f.write(f"pdf_count={generated}\n")

if __name__ == '__main__':
    main()
