#!/usr/bin/env python3
"""
Generate PDFs from markdown files with watermarks
Outputs PDFs to the same directory as the source .md files
"""

import os
import json
import subprocess
import tempfile
import sys
from datetime import datetime

# Add the scripts directory to Python path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

try:
    from watermark import add_watermark_to_pdf
except ImportError:
    # Fallback: define the function inline if import fails
    def add_watermark_to_pdf(input_pdf, output_pdf, watermark_text):
        print(f"⚠️  Watermarking disabled - would add: '{watermark_text}'")
        # Just copy the file as fallback
        import shutil
        shutil.copy(input_pdf, output_pdf)

def get_files_to_process():
    """Determine which .md files to process based on trigger type"""
    event_name = os.environ.get('EVENT_NAME', '')
    scope = os.environ.get('GENERATION_SCOPE', '')
    specific_files = os.environ.get('SPECIFIC_FILES', '')
    
    files_to_process = []
    
    if event_name == 'workflow_dispatch':
        print(f"Manual trigger with scope: {scope}")
        if scope == 'all':
            # Find all .md files in doc/ directory
            for root, dirs, files in os.walk('doc'):
                for file in files:
                    if file.endswith('.md'):
                        files_to_process.append(os.path.join(root, file))
            print(f"Found {len(files_to_process)} .md files")
        elif scope == 'specific' and specific_files:
            # Process specific files
            for file_path in specific_files.split(','):
                file_path = file_path.strip()
                if file_path.endswith('.md') and os.path.exists(file_path):
                    files_to_process.append(file_path)
                else:
                    print(f"Skipping invalid file: {file_path}")
    else:
        # Push event - we need to detect changed files differently
        print(f"Push event detected")
        # This will be handled by the workflow step that calls this script
    
    return files_to_process

def main():
    # Get environment variables
    actor = os.environ.get('ACTOR', 'Unknown')
    timestamp = os.environ.get('TIMESTAMP', '')
    custom_watermark = os.environ.get('CUSTOM_WATERMARK', '')
    
    # Parse the timestamp
    if not timestamp:
        timestamp = datetime.now().isoformat()
    
    try:
        dt = datetime.fromisoformat(timestamp.replace('Z', '+00:00'))
        formatted_time = dt.strftime("%Y-%m-%d %H:%M:%S UTC")
    except:
        formatted_time = timestamp
    
    # Create watermark text
    if custom_watermark:
        watermark_text = custom_watermark
    else:
        watermark_text = f"Generated by {actor} on {formatted_time}"
    
    print(f"📝 Watermark: {watermark_text}")
    
    # Get files to process
    files_to_process = get_files_to_process()
    
    if not files_to_process:
        print("ℹ️  No files to process")
        # Write empty file to indicate no PDFs generated
        with open('/tmp/generated_pdfs.txt', 'w') as f:
            f.write('')
        return
    
    print(f"🔄 Processing {len(files_to_process)} file(s)...")
    
    # Track generated PDFs
    generated_pdfs = []
    
    # Process each file
    for md_file in files_to_process:
        if not os.path.exists(md_file):
            print(f"⚠️  File not found: {md_file}")
            continue
            
        print(f"📄 Converting: {md_file}")
        
        # Create PDF filename (same directory, same base name, .pdf extension)
        pdf_file = md_file.replace('.md', '.pdf')
        
        try:
            # Create a temporary PDF first
            with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp_file:
                temp_pdf = tmp_file.name
            
            # Convert using pandoc
            cmd = [
                'pandoc', md_file,
                '-o', temp_pdf,
                '--pdf-engine=xelatex',
                '-V', 'geometry:margin=1in',
                '-V', 'fontsize=11pt',
                '--toc',  # Add table of contents
                '--toc-depth=3'
            ]
            
            print(f"Running command: {' '.join(cmd)}")
            result = subprocess.run(cmd, capture_output=True, text=True)
            
            if result.returncode != 0:
                print(f"❌ Pandoc error for {md_file}:")
                print(f"   {result.stderr}")
                continue
            
            # Add watermark to the generated PDF
            add_watermark_to_pdf(temp_pdf, pdf_file, watermark_text)
            
            # Clean up temp file
            if os.path.exists(temp_pdf):
                os.unlink(temp_pdf)
            
            # Track generated PDF
            generated_pdfs.append(pdf_file)
            print(f"✅ Generated: {pdf_file}")
            
        except Exception as e:
            print(f"❌ Error processing {md_file}: {str(e)}")
            import traceback
            traceback.print_exc()
            continue
    
    # Write list of generated PDFs to file for git commit step
    with open('/tmp/generated_pdfs.txt', 'w') as f:
        for pdf in generated_pdfs:
            f.write(pdf + '\n')
    
    print(f"🎉 PDF generation complete! Generated {len(generated_pdfs)} PDF(s).")

if __name__ == "__main__":
    main()
